echo "###############################################################################"
echo " make sure that the following lists are consistent to the dependencies defined"
echo " in the .nuspec files:"
echo "###############################################################################"
echo ""
echo "### KaVE.Commons ###"
echo ""
echo "<dependencies>"
cat ../KaVE.Commons/packages.config | grep "<package id=" | sed -e 's/^[ \t]*//' | sed -e "s/\<package/dependency/" | sed -e "s/targetFramework="[^/]*"//"
echo "</dependencies>"
echo ""
echo ""
echo "### KaVE.TestCommons.nuspec ###"
echo ""
echo "<dependencies>"
cat ../KaVE.Commons.TestUtils/packages.config | grep "<package id=" | sed -e 's/^[ \t]*//' | sed -e "s/\<package/dependency/" | sed -e "s/targetFramework="[^/]*"//"
echo "</dependencies>"
echo ""
read